version: "3.8"
services:
  server:
    build: .
    container_name: warehouse-server
    entrypoint: ./entrypoint-server.sh
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/warehouse-intexsoft-intership
    env_file:
      - .env
    depends_on:
      - db

  worker:
    build: .
    container_name: warehouse-worker
    entrypoint: ./entrypoint-celery.sh
    volumes:
      - .:/usr/warehouse-intexsoft-intership
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: warehouse-db
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5430:5432"

  rabbitmq:
    image: rabbitmq:3.9.0-management-alpine
    container_name: rabbit
    environment:
      RABBITMQ_BROKER: ${RABBITMQ_BROKER}
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    name: external-example