version: "3.8"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/warehouse-intexsoft-intership
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5430:5430"
